# Generated by Django 5.2 on 2025-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
